In [1]:
import numpy as np

In [2]:
# Creating 2D array
arr = np.array([
    [6, -8, 73, -110],
    [np.nan, -8, 0, 94]
])

print("Original Array:\n")
print(arr)

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("\nArray after replacing NaN with 0:\n")
print(arr)

# Interchange rows and columns (Transpose)
transpose_arr = arr.T

print("\nTranspose Array:\n")
print(transpose_arr)

Original Array:

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

Array after replacing NaN with 0:

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Transpose Array:

[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [3]:
# Creating 3D array
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Original Shape:", arr.shape)

# Move axes
new_arr = np.moveaxis(arr, 0, 2)

print("\nNew Shape:", new_arr.shape)

print("\nModified Array:\n")
print(new_arr)

Original Shape: (2, 2, 2)

New Shape: (2, 2, 2)

Modified Array:

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [4]:
# Creating array
arr = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])

print("Original Array:\n")
print(arr)

# Find column means ignoring NaN
col_mean = np.nanmean(arr, axis=0)

# Find indices where NaN exists
inds = np.where(np.isnan(arr))

# Replace NaN with column mean
arr[inds] = np.take(col_mean, inds[1])

print("\nArray after replacing NaN with column average:\n")
print(arr)

Original Array:

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]

Array after replacing NaN with column average:

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [5]:
# Creating array
arr = np.array([10, -5, 20, -8, 30, -1])

print("Original Array:\n")
print(arr)

# Replace negative values with 0
arr[arr < 0] = 0

print("\nModified Array:\n")
print(arr)

Original Array:

[10 -5 20 -8 30 -1]

Modified Array:

[10  0 20  0 30  0]
