In [1]:
import numpy as np

In [2]:
arr1 = np.array([10, 20, 30])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

combined = np.vstack((arr2, arr1))

print(combined)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


In [3]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


In [4]:
arr = np.array([10, 20, 30, 40, 50])

reverse_arr = arr[::-1]

print(reverse_arr)

[50 40 30 20 10]


In [5]:
arr = np.array([10, 50, 20, 90, 30])

print("Maximum Value:", np.max(arr))

Maximum Value: 90


In [6]:
arr = np.array([10, 50, 20, 90, 30])

print("Minimum Value:", np.min(arr))

Minimum Value: 10


In [7]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

rows, cols = arr.shape

print("Rows:", rows)
print("Columns:", cols)

Rows: 2
Columns: 3


In [8]:
arr = np.array([
    [10, 20],
    [30, 40]
])

for row in arr:
    for value in row:
        print(value)

10
20
30
40


In [9]:
arr = np.array([
    [10, 20],
    [30, 40]
])

print(arr[1][0])

30


In [10]:
arr = np.array([
    [1, 2],
    [3, 4]
])

total = 0

for row in arr:
    for value in row:
        total += value

print("Sum =", total)

Sum = 10


In [11]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [12]:
import numpy as np

a = np.array([10, 20, 30])

b = np.array([1, 2, 3])

print(a - b)

[ 9 18 27]


In [13]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

print(a * b)

[ 4 10 18]


In [14]:
a = np.array([10, 20, 30])

b = np.array([2, 4, 5])

print(a / b)

[5. 5. 6.]


In [15]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for matrix in arr:
    for row in matrix:
        for value in row:
            print(value)

1
2
3
4
5
6
7
8


In [16]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for value in np.nditer(arr):
    print(value)

1
2
3
4
5
6
7
8


In [17]:
from statistics import mode

arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

# Average Array
avg = (arr1 + arr2) / 2

print("Average Array:\n")
print(avg)

# Combine Arrays
combined = np.concatenate((arr1, arr2))

# Mean
print("\nMean =", np.mean(combined))

# Median
print("Median =", np.median(combined))

# Mode
print("Mode =", mode(combined.flatten()))

Average Array:

[[4. 5. 6.]
 [7. 8. 9.]]

Mean = 6.5
Median = 6.5
Mode = 1
